// Output
// Failed function call 'foo' must be followed by a 'then', 'succeeded' or 'failed' block or statement

fun foo(a: Text, b: Num): Null? {
    echo a + " World"
    echo b * 2
    fail 1
}

const a = "Hello"
const b = 21

echo foo(a, b)
echo foo("This", 12)
